server:
  port: 8080
spring:
  mail:
    # 163邮箱的地址为smtp.163.com，直接填写即可
    host: smtp.163.com
    # 你申请的163邮箱
    username: m19164221189@163.com
    # 注意密码是在开启smtp/pop3时自动生成的，记得保存一下，不然就找不到了
    password: RAKTCQGORXBPIVPR
    ssl:
      enabled: true
app:
  data-path: D:/Develop/zstrunk-frontend/data
knife4j:
  # 开启增强配置
  enable: true
  # 标识是否生产环境：true-生产环境关闭文档，false-显示文档
  production: true

